[build]
  publish = "public"
  command = "yarn build"
[build.environment]
  YARN_VERSION = "1.3.2"
  YARN_FLAGS = "--no-ignore-optional"
[[plugins]]
package = "netlify-plugin-gatsby-cache"

[[plugins]]
package = "netlify-plugin-checklinks"

[[plugins]]
package = "netlify-plugin-no-more-404"

[[plugins]]
package = "netlify-plugin-a11y"

  [plugins.inputs]
  checkPaths = ['/posts']
  resultMode = "warn"

[[plugins]]
package = "netlify-plugin-subfont"
