[build]
  publish = "public"
  command = "yarn build"
[build.environment]
  YARN_VERSION = "1.22.19"
  YARN_FLAGS = "--no-ignore-optional"
  NODE_VERSION = "20.14.0"
[[plugins]]
package = "netlify-plugin-gatsby-cache"

[[plugins]]
package = "netlify-plugin-checklinks"

[[plugins]]
package = "netlify-plugin-no-more-404"

[[plugins]]
package = "netlify-plugin-subfont"
