version: 2

defaults: &defaults
  docker:
    - image: circleci/node:10.17.0
  working_directory: ~/kobi.kadosh.me

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run: yarn install --frozen-lockfile
      - run: npm i eslint
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}

  lint:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run: yarn flow
      - run: yarn run lint:scss
      - run:
          command: |
            mkdir -p test-results/eslint/
            npx eslint --cache --ext .js,.jsx . --format junit --output-file test-results/eslint/eslint.xml
          when: always
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results

  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Run tests with JUnit as reporter
          command: yarn test --ci --runInBand --no-cache  --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: "test-results/jest"
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results

  coverage:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "yarn.lock" }}
      - run: yarn test:coverage --runInBand --no-cache
      - store_artifacts:
          path: coverage
      - save_cache:
          key: coverage-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - coverage

  codecov:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "yarn.lock" }}
      - restore_cache:
          keys:
            - coverage-{{ .Environment.CIRCLE_SHA1 }}
      - run: yarn global add codecov
      - run: yarn codecov
    
workflows:
  version: 2
  test:
    jobs:
      - install
      - lint:
          requires:
            - install
      - test:
          requires:
            - install
      - coverage:
          requires:
            - install
      - codecov:
          requires:
            - coverage