name: Audit pull request
on:
  pull_request:
    branches:
      - master

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Netlify Preview
        uses: jakepartusch/wait-for-netlify-action@v1
        with:
          # The Netlify site name to test against
          site_name: kobi-kadosh-blog
      - name: Audit Netlify deploy preview
        uses: jakejarvis/lighthouse-action@master
        with:
          netlify_site: 'kobi-kadosh-blog.netlify.app/posts/write-less-read-more'
      - uses: actions/upload-artifact@master
        with:
          name: report
          path: './report'
